### ISSUE TITLE
Enhancement: Add helper functions to encode/decode iptc.Rule()

### ISSUE THREAD

**Issue by jllorente** [ldx/python-iptables#219]
Hi,
I've noticed how sometimes it can get a bit tricky to configure a rule properly, or even to print out all the fields.

I have created couple of functions that facilitate these tasks (currently only for IPv4):
encode_rule_from_dict_v4(rule_d): Receives a rule in a dictionary format and returns a valid iptc.Rule() object.
decode_rule_to_dict_v4(iptc_rule): Receives an iptc.Rule() objects and return the rule in dictionary format.

The dictionary looks like this: {'comment': {'comment': 'Invalid TCP SYN packet'}, 'target': 'DROP', 'protocol': 'tcp', 'conntrack': {'ctstate': 'NEW'}, 'tcp': {'tcp-flags': ['!', 'FIN,SYN,RST,ACK', 'SYN']}}}

@ldx  Would this be something worth adding ? And if so, in what file should it be added?
Currently I have all these functions on a separate file, a helper, where I  import iptc...

Thanks!

**Comment by pepoluan** [comment]
_Very_ interesting! I'm neutral _but_ tending to +1 on this.

In any case, my interest is kinda tangential: If we can settle on the dict keys & structure/hierarchy, we can then expand this to a YAML-based netfilter configurator. E.g.:

```yaml
- description: Example rule
  comment: ShortComment
  target: DROP
  protocol: tcp  # Can be implicit if 'tcp' key is found?
  conntrack:
    ctstate: NEW
  tcp:
    tcp-flags:
      negate: yes
      mask: FIN, SYN, RST, ACK
      match: SYN
```
